########################
# Persistence settings #
########################

# RDB snapshots (quick recovery)
save 900 1
save 300 10
save 60 10000
rdbcompression yes
rdbchecksum yes
stop-writes-on-bgsave-error yes

# AOF (durability)
appendonly yes
appendfsync everysec
aof-use-rdb-preamble yes

# AOF rewrite
auto-aof-rewrite-percentage 100
auto-aof-rewrite-min-size 64mb
